services:
  settings:
    profiles:
      url: ${url}
    
configuration:
  rest:
    employee-profiles:
      url: ${url}
      port: 443

  database:
    employee:
      url: ${url}
      user: ${user}
      password: ${password}
  

  

